name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pregunta 01
      id: pregunta-01
      uses: education/autograding-command-grader@v1
      with:
        test-name: Pregunta 01
        setup-command: pip3 install pandas scikit-learn
        command: python3 tests.py 01
        timeout: 1
        max-score: 1
    - name: Pregunta 02
      id: pregunta-02
      uses: education/autograding-command-grader@v1
      with:
        test-name: Pregunta 02
        setup-command: pip3 install pandas scikit-learn
        command: python3 tests.py 02
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        PREGUNTA-01_RESULTS: "${{steps.pregunta-01.outputs.result}}"
        PREGUNTA-02_RESULTS: "${{steps.pregunta-02.outputs.result}}"
      with:
        runners: pregunta-01,pregunta-02
